### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by fabltd** [alibabzo/esp32-rmt-rf#1]
Hi 

I have some questions is here the best place to post them?

I am looking to adapt what you have done what did you use as a base reference?

JT

**Comment by alistairbill** [comment]
Hello,

You could start by looking at [the esp-idf infrared example](https://github.com/espressif/esp-idf/blob/d57890cdff10648371bc13956230635d2944d254/examples/peripherals/rmt_nec_tx_rx/main/infrared_nec_main.c) and the [Arduino RMT example](https://github.com/espressif/arduino-esp32/blob/cec3fca4ad4a39feb463f9298ab3238819732d50/libraries/ESP32/examples/RMT/RMTLoopback/RMTLoopback.ino).

**Comment by fabltd** [comment]
Hi Still suck. Interested in customising this for my requirment?
